# Generated by Django 5.2 on 2025-05-01 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The main title of the event.", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="A detailed description of the event"),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="a url to an image representing the event (not necessary)",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The price of a single ticket.",
                        max_digits=8,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="The venue or address where the event takes place.",
                        max_length=255,
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        help_text="The date and time when the event starts."
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        help_text="The date and time when the event ends."
                    ),
                ),
            ],
        ),
    ]
