# Generated by Django 5.2 on 2025-05-02 16:54


from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model() # Get the active User model

    # *** CHANGE THESE VALUES ***
    DJANGO_SUPERUSER_USERNAME = 'maxld' 
    DJANGO_SUPERUSER_EMAIL = 'draheim@wustl.edu'
    DJANGO_SUPERUSER_PASSWORD = 'drahe002'

    # Check if user already exists 
    if User.objects.filter(username=DJANGO_SUPERUSER_USERNAME).exists():
        print(f"\nSuperuser '{DJANGO_SUPERUSER_USERNAME}' already exists. Skipping creation.")
        return

    # Create the superuser
    print(f"\nCreating superuser '{DJANGO_SUPERUSER_USERNAME}'...")
    User.objects.create_superuser(
        username=DJANGO_SUPERUSER_USERNAME,
        email=DJANGO_SUPERUSER_EMAIL,
        password=DJANGO_SUPERUSER_PASSWORD
    )
    print("Superuser created successfully.")


class Migration(migrations.Migration):

    dependencies = [
        # Make sure this dependency points to your previous migration in the 'events' app
        ('events', '0001_initial'),
    ]

    operations = [
        # tells Django to run our custom Python function during the migrate process
        migrations.RunPython(create_superuser),
    ]